
import { WaveTune } from '../../../code';

export const tunePulse = new WaveTune({
  name: 'tunePulse',
  timeSignature: [8, 8],
  instruments: {
    guitar: {
      on: false,
      parts: {},
      sequence: []
    },

    bass: {
      on: false,
      parts: {},
      sequence: []
    },

    drums: {
      on: true,
      parts: {
        intro:                    ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        transition:               ['k', '-', '-', '-', '-', '-'],
        transition_empty:         ['-', '-', '-', '-', '-', '-'],
        chorus_intro:             ['-', '-', '-', '-', '-', '-'],
        chorus:                   ['-', '-', '-', 'k', '-', '-'],
        chorus_empty:             ['-', '-', '-', '-', '-', '-'],
        verse:                    ['-', '-', '-', '-', '-', '-'],
        verse2:                   ['-', '-', '-', '-', '-', '-'],
        bridge_intro:             ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        bridge_intro2:            ['k', '-', '-', '-', '-', '-', '-', '-', '-'],
        bridge_riff1:             ['-', '-', '-', 'k', '-', '-'],
        bridge_riff1_empty:       ['-', '-', '-', '-', '-', '-'],
        bridge_riff2:             ['k', '-', '-', '-', '-', '-', '-', '-', '-'],
        bridge_riff2_empty:       ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        verse_distortion:         ['-', '-', '-', '-', '-', '-'],
        verse2_distortion:        ['-', '-', '-', '-', '-', '-'],
        bridge_riff3:             ['k', '-', '-', '-', '-', '-', '-', '-', '-'],
        bridge_riff3_empty:       ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        bridge_riff4:             ['k', '-', '-', '-', '-', '-'],
        bridge_riff4_empty:       ['-', '-', '-', '-', '-', '-'],
        outro_distortion:         ['k', '-', '-', '-', '-', '-'],
        outro_distortion_empty:   ['-', '-', '-', '-', '-', '-'],
        outro_distortion2:        ['k', '-', '-', '-', '-', '-', '-', '-', '-'],
        outro_distortion2_empty:  ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        outro:                    ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        outro_end:                ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
        outro_end2:               ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
      },
      sequence: [
        { part: 'intro', repeat: 8 },
        { part: 'transition', repeat: 1 },
        { part: 'transition_empty', repeat: 3 },
        { part: 'transition', repeat: 1 },
        { part: 'transition_empty', repeat: 3 },
        { part: 'transition', repeat: 1 },
        { part: 'transition_empty', repeat: 3 },
        { part: 'transition', repeat: 1 },
        { part: 'transition_empty', repeat: 3 },

        { part: 'chorus_intro', repeat: 8 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },

        { part: 'verse', repeat: 8 },
        { part: 'verse2', repeat: 8 },
        { part: 'verse', repeat: 8 },
        { part: 'verse2', repeat: 8 },
        { part: 'chorus_intro', repeat: 8 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },

        { part: 'verse', repeat: 8 },
        { part: 'verse2', repeat: 8 },

        { part: 'chorus_intro', repeat: 8 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },
        { part: 'chorus', repeat: 1 },
        { part: 'chorus_empty', repeat: 3 },

        { part: 'bridge_intro', repeat: 8 },
        { part: 'bridge_intro2', repeat: 1 },
        { part: 'bridge_intro', repeat: 1 },
        { part: 'bridge_intro2', repeat: 1 },
        { part: 'bridge_intro', repeat: 1 },
        { part: 'bridge_intro2', repeat: 1 },
        { part: 'bridge_intro', repeat: 1 },
        { part: 'bridge_intro2', repeat: 1 },
        { part: 'bridge_intro', repeat: 1 },

        { part: 'bridge_riff1', repeat: 1 },
        { part: 'bridge_riff1_empty', repeat: 3 },
        { part: 'bridge_riff1', repeat: 1 },
        { part: 'bridge_riff1_empty', repeat: 3 },
        { part: 'bridge_riff1', repeat: 1 },
        { part: 'bridge_riff1_empty', repeat: 3 },
        { part: 'bridge_riff1', repeat: 1 },
        { part: 'bridge_riff1_empty', repeat: 3 },
        { part: 'bridge_riff2', repeat: 1 },
        { part: 'bridge_riff2_empty', repeat: 3 },
        { part: 'bridge_riff2', repeat: 1 },
        { part: 'bridge_riff2_empty', repeat: 3 },

        { part: 'verse_distortion', repeat: 8 },
        { part: 'bridge_riff2', repeat: 1 },
        { part: 'bridge_riff2_empty', repeat: 3 },
        { part: 'bridge_riff2', repeat: 1 },
        { part: 'bridge_riff2_empty', repeat: 3 },
        { part: 'verse2_distortion', repeat: 8 },

        { part: 'bridge_riff3', repeat: 1 },
        { part: 'bridge_riff3_empty', repeat: 1 },
        { part: 'bridge_riff3', repeat: 1 },
        { part: 'bridge_riff3_empty', repeat: 1 },
        { part: 'bridge_riff3', repeat: 1 },
        { part: 'bridge_riff3_empty', repeat: 1 },
        { part: 'bridge_riff3', repeat: 1 },
        { part: 'bridge_riff3_empty', repeat: 1 },

        { part: 'bridge_riff4', repeat: 1 },
        { part: 'bridge_riff4_empty', repeat: 3 },
        { part: 'bridge_riff4', repeat: 1 },
        { part: 'bridge_riff4_empty', repeat: 3 },
        { part: 'bridge_riff4', repeat: 1 },
        { part: 'bridge_riff4_empty', repeat: 3 },
        { part: 'bridge_riff4', repeat: 1 },
        { part: 'bridge_riff4_empty', repeat: 3 },

        { part: 'outro_distortion', repeat: 1 },
        { part: 'outro_distortion_empty', repeat: 7 },
        { part: 'outro_distortion', repeat: 1 },
        { part: 'outro_distortion_empty', repeat: 7 },
        { part: 'outro_distortion', repeat: 1 },
        { part: 'outro_distortion_empty', repeat: 7 },
        { part: 'outro_distortion', repeat: 1 },
        { part: 'outro_distortion_empty', repeat: 7 },
        { part: 'outro_distortion2', repeat: 1 },
        { part: 'outro_distortion2_empty', repeat: 3 },
        { part: 'outro_distortion2', repeat: 1 },
        { part: 'outro_distortion2_empty', repeat: 3 },
        { part: 'outro', repeat: 16 },
        { part: 'outro_end', repeat: 4 },
        { part: 'outro_end2', repeat: 4 },
      ],
      noteLength: '8n'
    },

    hihat: {
      on: false,
      parts: {},
      sequence: []
    }
  },
  bpm: 104
})
